apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}-app
  labels:
    app: {{ include "app.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "app.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "app.name" . }}
    spec:
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "app.fullname" . }}
      {{- end }}
      containers:
      - name: {{ include "app.name" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.app.targetPort }}
        {{- if or .Values.env.plain .Values.configMap.data .Values.secret.data }}
        env:
        {{- range .Values.env.plain }}
        - name: {{ .name }}
          value: {{ .value | quote }}
        {{- end }}
        {{- if .Values.configMap.enabled }}
        {{- range $key, $value := .Values.configMap.data }}
        - name: {{ $key }}
          valueFrom:
            configMapKeyRef:
              name: {{ include "app.fullname" $ }}
              key: {{ $key }}
        {{- end }}
        {{- end }}
        {{- if .Values.secret.enabled }}
        {{- range $key, $value := .Values.secret.data }}
        - name: {{ $key }}
          valueFrom:
            secretKeyRef:
              name: {{ include "app.fullname" $ }}
              key: {{ $key }}
        {{- end }}
        {{- end }}
        {{- end }}
        readinessProbe:
          httpGet:
            path: {{ .Values.ingress.healthcheckPath | default "/health" }}
            port: {{ .Values.service.app.targetPort }}
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: {{ .Values.ingress.healthcheckPath | default "/health" }}
            port: {{ .Values.service.app.targetPort }}
          initialDelaySeconds: 15
          periodSeconds: 20
