apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    app: {{ include "app.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.app.port }}
      targetPort: {{ .Values.service.app.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "app.name" . }}
